export interface NetworkConnection {
    branch_connection_id: number;
    state_name: string | null;
    zone_name: string | null;
    branch_name: string;
    ISP_provider: string;
    ISP_provider_name: string;
    connection_status: string;
    ISP_user_name: string;
    ISP_password: string;
    WAN_IP: string | null;
    LAN_IP: string | null;
    Device_Type: string;
    Device_serial_no: number | null;
    BW_capasity: string;
    which_section_connection_is_provided: string;
    price_PM_ex_GST: number | null;
    GST_per: number | null;
    price_PM_in_GST: number | null;
    total_price: number | null;
    billing_frequency_in_months: number | null;
    billing_company: string;
    last_payment_amount: number | null;
    last_payment_date: string | null;
    recharge_from: string | null;
    recharge_to: string | null;
    last_payment_duration: string;
    next_payment_due_date: string | null;
    approval_status: number | null;
    approval_status_name: string | null;
    invoice_submitted_date: string | null;
    payment_status: number | null;
    IT_remarks: string;
    has_class_room_wifi: boolean;
    count_class_room_wifi: number | null;
    branch: number;
    ISP_provider_contact: number | null;
    payment_status_name: string | null;
  }